CREATE TABLE reg_resolucion_final (
	id int IDENTITY(1,1) NOT NULL,
	id_registro int NOT NULL,
	id_queja int NOT NULL,
	id_resultado_audiencia int,
	anio   int,
	id_tipo_registro int NOT NULL,
	consumidor_nombre varchar(150) null,
	proveedor_nombre varchar(150) null,
	codigo varchar(30)  NULL,
	usuario_creacion int,
	version varchar(30)  NULL,
	quejanumero int NULL,
	fecha_creacion datetime NULL,
	creado_por int NOT NULL,
	correlativo varchar(30)  NULL,
	CONSTRAINT PK_reg_resolucion_final PRIMARY KEY (id),
	CONSTRAINT FK_reg_resolucion_final FOREIGN KEY (id_tipo_registro) REFERENCES diaco_cat_tipo_registro(id_tipo_registro),
	CONSTRAINT FK_reg_resolucion_final_diaco_queja FOREIGN KEY (id_queja) REFERENCES diaco_queja(id_queja),
	CONSTRAINT FK_reg_resolucion_final_diaco_registro FOREIGN KEY (id_registro) REFERENCES diaco_registro(id_registro),
	CONSTRAINT FK_reg_resolucion_final_diaco_usuario FOREIGN KEY (creado_por) REFERENCES diaco_usuario(id_usuario)
);
