CREATE TABLE reg_cedula_notificacion_citacion_juridico (
	id int IDENTITY(1,1) NOT NULL,
	id_registro int NOT NULL,
	id_queja int NOT NULL,
	id_tipo_registro int NOT NULL,
	id_audiencia int NOT NULL,
	codigo varchar(30)   NULL,
	version varchar(30)   NULL,
	quejanumero int NULL,
	telefono  varchar(100),
	municipio  varchar (100),
	departamento varchar(100),
	direccion    varchar(300),
	nombre       varchar(100),
	fecha_citacion datetime NULL,
	fecha_creacion datetime NULL,
	creado_por int NOT NULL,
	correlativo varchar(30)  NULL,
	es_consumidor_proveedor varchar(1),
	CONSTRAINT PK_reg_cedula_notificacion_citacion_juridico PRIMARY KEY (id),
	CONSTRAINT FK_reg_cedula_notificacion_citacion_juridico FOREIGN KEY (id_tipo_registro) REFERENCES diaco_cat_tipo_registro(id_tipo_registro),
	CONSTRAINT FK_reg_cedula_notificacion_citacion_juridico_diaco_queja FOREIGN KEY (id_queja) REFERENCES diaco_queja(id_queja),
	CONSTRAINT FK_reg_cedula_notificacion_citacion_juridico_diaco_registro FOREIGN KEY (id_registro) REFERENCES diaco_registro(id_registro),
	CONSTRAINT FK_reg_cedula_notificacion_citacion_juridico_diaco_usuario FOREIGN KEY (creado_por) REFERENCES diaco_usuario(id_usuario)
);
